/* 이야기 속 문학 한 줄: 저작권이 끝난 작가(사망 70년 이상)의 짧은 구절을 우리 말투로 감싸요.
   번역은 모두 직접 했어요(원문이 그 언어인 경우만 원문). **…** 부분이 굵게 보여요.
   s 계절 · t 시간대(morning/day/evening/night) · w 날씨(clear/cloud/rain/snow) — 비어 있으면 언제든 */
const LIT = [
  // ── 라이너 마리아 릴케 (1875–1926)
  { s: 'autumn', ko: '릴케는 이맘때를 두고 **여름은 참으로 찬란했다**고 썼어요.', en: 'Rilke wrote of this time of year: **the summer was immense**.', ja: 'リルケはこの季節を、**夏はじつに偉大だった**と書きました。', es: 'Rilke escribió sobre esta época del año: **el verano fue inmenso**.', fr: 'Rilke a écrit de cette saison : **l’été fut très grand**.' },
  { s: 'autumn', ko: '릴케는 가을날 **들판에 바람을 풀어 놓아 달라**고 노래했어요.', en: 'Rilke asked the autumn day to **let the winds loose on the fields**.', ja: 'リルケは秋の日に、**野に風を放ってください**と歌いました。', es: 'Rilke pidió al día de otoño que **soltara los vientos sobre los campos**.', fr: 'Rilke demandait au jour d’automne de **lâcher les vents sur les plaines**.' },
  { s: 'autumn', ko: '릴케는 **잎이 떨어진다, 먼 데서 오듯이**라고 썼어요.', en: 'Rilke wrote, **the leaves are falling, falling as if from far away**.', ja: 'リルケは、**木の葉が落ちる、遠くから来るように**と書きました。', es: 'Rilke escribió: **caen las hojas, caen como desde lejos**.', fr: 'Rilke a écrit : **les feuilles tombent, tombent comme de loin**.' },
  { ko: '릴케는 젊은 시인에게 **지금은 질문을 살아 보라**고 했어요.', en: 'Rilke told a young poet to **live the questions now**.', ja: 'リルケは若い詩人に、**いまは問いそのものを生きなさい**と言いました。', es: 'Rilke le dijo a un joven poeta que **viviera ahora las preguntas**.', fr: 'Rilke conseillait à un jeune poète de **vivre maintenant les questions**.' },
  // ── 윤동주 (1917–1945)
  { t: 'night', ko: '**오늘 밤에도 별이 바람에 스치운다**고, 윤동주는 썼어요.', en: '**Tonight, too, the stars are brushed by the wind**, wrote Yun Dong-ju.', ja: '**今夜も星が風にこすられる**と、尹東柱は書きました。', es: '**Esta noche también el viento roza las estrellas**, escribió Yun Dong-ju.', fr: '**Ce soir encore, le vent frôle les étoiles**, écrivait Yun Dong-ju.' },
  { s: 'autumn', ko: '윤동주는 **계절이 지나가는 하늘은 가을로 가득 차 있다**고 썼어요.', en: 'Yun Dong-ju wrote that **the sky where the seasons pass is full of autumn**.', ja: '尹東柱は、**季節の過ぎゆく空は秋でいっぱいだ**と書きました。', es: 'Yun Dong-ju escribió que **el cielo por donde pasan las estaciones está lleno de otoño**.', fr: 'Yun Dong-ju a écrit que **le ciel où passent les saisons est rempli d’automne**.' },
  { t: 'night', w: 'clear', ko: '윤동주는 **별 하나에 추억과, 별 하나에 사랑**을 헤아렸어요.', en: 'Yun Dong-ju counted **one star for a memory, one star for love**.', ja: '尹東柱は、**星ひとつに思い出と、星ひとつに愛と**数えました。', es: 'Yun Dong-ju contaba **una estrella para un recuerdo, una estrella para el amor**.', fr: 'Yun Dong-ju comptait **une étoile pour un souvenir, une étoile pour l’amour**.' },
  { t: 'morning', ko: '윤동주는 **어제도 가고 오늘도 갈 나의 길, 새로운 길**이라고 썼어요.', en: 'Yun Dong-ju wrote of **the road I walked yesterday and will walk today, a new road**.', ja: '尹東柱は、**きのうも行き、きょうも行くわたしの道、新しい道**と書きました。', es: 'Yun Dong-ju escribió sobre **el camino que anduve ayer y andaré hoy, un camino nuevo**.', fr: 'Yun Dong-ju a écrit : **le chemin pris hier et que je prendrai aujourd’hui, un chemin nouveau**.' },
  { s: 'autumn', ko: '윤동주는 **단풍잎 같은 가을이 뚝뚝 떨어진다**고 썼어요.', en: 'Yun Dong-ju wrote that **autumn falls drop by drop, like maple leaves**.', ja: '尹東柱は、**紅葉のような秋がぽとぽと落ちる**と書きました。', es: 'Yun Dong-ju escribió que **el otoño cae gota a gota, como hojas de arce**.', fr: 'Yun Dong-ju a écrit que **l’automne tombe goutte à goutte, comme des feuilles d’érable**.' },
  { s: 'autumn', ko: '윤동주는 우물 속에 **달이 밝고 구름이 흐르고 가을이 있다**고 썼어요.', en: 'Yun Dong-ju looked into a well where **the moon was bright, clouds drifted, and there was autumn**.', ja: '尹東柱は井戸の中に、**月が明るく雲が流れ、秋がある**と書きました。', es: 'Yun Dong-ju vio en un pozo que **la luna brillaba, pasaban las nubes y había otoño**.', fr: 'Yun Dong-ju voyait dans un puits **la lune claire, les nuages qui passent, et l’automne**.' },
  // ── 김소월 (1902–1934)
  { t: 'night', ko: '김소월은 **봄 가을 없이 밤마다 돋는 달도 예전엔 미처 몰랐다**고 했어요.', en: 'Kim Sowol said he **never noticed the moon that rises every night, spring or autumn**.', ja: '金素月は、**春も秋もなく毎晩のぼる月にも、以前は気づかなかった**と言いました。', es: 'Kim Sowol dijo que **antes no se fijaba en la luna que sale cada noche, sea primavera u otoño**.', fr: 'Kim Sowol disait **n’avoir jamais remarqué la lune qui se lève chaque nuit, printemps ou automne**.' },
  { s: 'spring', ko: '김소월은 **산에는 꽃 피네, 갈 봄 여름 없이 꽃이 피네**라고 노래했어요.', en: 'Kim Sowol sang, **flowers bloom on the mountain, autumn, spring or summer, flowers bloom**.', ja: '金素月は、**山には花が咲く、秋も春も夏もなく花が咲く**と歌いました。', es: 'Kim Sowol cantó: **en la montaña florecen flores, en otoño, primavera o verano**.', fr: 'Kim Sowol chantait : **sur la montagne les fleurs s’ouvrent, automne, printemps ou été**.' },
  { w: 'clear', t: 'day', ko: '김소월은 **반짝이는 금모래 빛과 갈잎의 노래**가 있는 강변을 그렸어요.', en: 'Kim Sowol pictured a riverside with **glittering golden sand and the song of reeds**.', ja: '金素月は、**きらめく金の砂と葦の歌**のある川辺を描きました。', es: 'Kim Sowol imaginó una orilla con **arena dorada que brilla y la canción de los juncos**.', fr: 'Kim Sowol peignait une rive de **sable d’or scintillant et de chant des roseaux**.' },
  // ── 이효석 (1907–1942)
  { t: 'night', s: 'autumn', ko: '이효석은 이런 밤의 달빛을 **소금을 뿌린 듯 흐뭇하다**고 했어요.', en: 'Lee Hyo-seok said moonlight on a night like this looks **like scattered salt**.', ja: '李孝石はこんな夜の月明かりを、**塩をまいたように満ち足りている**と書きました。', es: 'Lee Hyo-seok decía que la luz de luna en una noche así parece **sal esparcida**.', fr: 'Lee Hyo-seok disait que le clair de lune d’une telle nuit ressemble à **du sel répandu**.' },
  { s: 'autumn', ko: '이효석은 낙엽 타는 냄새에서 **갓 볶아 낸 커피 냄새**가 난다고 썼어요.', en: 'Lee Hyo-seok wrote that burning leaves smell **like freshly roasted coffee**.', ja: '李孝石は、落ち葉を焚く匂いは**煎りたてのコーヒーの香り**がすると書きました。', es: 'Lee Hyo-seok escribió que las hojas quemadas huelen **a café recién tostado**.', fr: 'Lee Hyo-seok écrivait que les feuilles brûlées sentent **le café fraîchement torréfié**.' },
  // ── 김유정 (1908–1937)
  { s: 'spring', ko: '김유정은 봄꽃 냄새를 **알싸한, 그리고 향긋한** 냄새라고 썼어요.', en: 'Kim Yu-jeong described the scent of spring flowers as **sharp, and then sweet**.', ja: '金裕貞は春の花の匂いを、**ぴりっとして、そしてかぐわしい**と書きました。', es: 'Kim Yu-jeong describió el olor de las flores de primavera como **picante, y luego dulce**.', fr: 'Kim Yu-jeong décrivait le parfum des fleurs de printemps comme **piquant, puis doux**.' },
  // ── 정지용 (1902–1950)
  { t: 'evening', ko: '정지용은 **황소가 금빛 게으른 울음을 우는** 저녁을 그렸어요.', en: 'Jeong Ji-yong pictured an evening where **an ox lows a lazy, golden cry**.', ja: '鄭芝溶は、**牛が金色のけだるい声で鳴く**夕暮れを描きました。', es: 'Jeong Ji-yong imaginó una tarde en que **un buey muge con un lamento perezoso y dorado**.', fr: 'Jeong Ji-yong peignait un soir où **un bœuf pousse un meuglement paresseux et doré**.' },
  { ko: '정지용은 **보고 싶은 마음 호수만 하니 눈 감을 밖에**라고 썼어요.', en: 'Jeong Ji-yong wrote, **my longing is as wide as a lake, so I can only close my eyes**.', ja: '鄭芝溶は、**会いたい心は湖ほどだから、目を閉じるしかない**と書きました。', es: 'Jeong Ji-yong escribió: **mis ganas de verte son grandes como un lago; solo puedo cerrar los ojos**.', fr: 'Jeong Ji-yong a écrit : **mon envie de te voir est vaste comme un lac, je ne peux que fermer les yeux**.' },
  { ko: '정지용은 고향을 **옛이야기 지줄대는 실개천이 회돌아 나가는 곳**이라고 했어요.', en: 'Jeong Ji-yong remembered home as **where a little stream winds away, murmuring old stories**.', ja: '鄭芝溶は故郷を、**昔話をささやく小川がめぐり流れるところ**と書きました。', es: 'Jeong Ji-yong recordaba su tierra como **el lugar donde un arroyo serpentea murmurando historias antiguas**.', fr: 'Jeong Ji-yong se souvenait de chez lui comme du lieu **où un ruisseau s’en va en murmurant de vieilles histoires**.' },
  // ── 한용운 (1879–1944)
  { s: 'autumn', ko: '한용운은 **고요히 떨어지는 오동잎**을 누구의 발자취냐고 물었어요.', en: 'Han Yong-un asked whose footsteps were **the paulownia leaves falling so quietly**.', ja: '韓龍雲は、**静かに落ちる桐の葉**は誰の足跡かと問いました。', es: 'Han Yong-un preguntó de quién eran los pasos de **las hojas de paulonia que caen en silencio**.', fr: 'Han Yong-un se demandait de qui étaient les pas des **feuilles de paulownia qui tombent en silence**.' },
  { w: 'cloud', ko: '한용운은 구름 틈으로 **언뜻언뜻 보이는 푸른 하늘**을 누구의 얼굴이냐고 물었어요.', en: 'Han Yong-un asked whose face was **the blue sky glimpsed through the clouds**.', ja: '韓龍雲は、雲の切れ間から**ちらちら見える青空**は誰の顔かと問いました。', es: 'Han Yong-un preguntó de quién era el rostro del **cielo azul que asoma entre las nubes**.', fr: 'Han Yong-un se demandait à qui était le visage du **ciel bleu entrevu entre les nuages**.' },
  // ── 이육사 (1904–1944)
  { s: 'summer', ko: '이육사는 **내 고장 칠월은 청포도가 익어 가는 시절**이라고 썼어요.', en: 'Yi Yuksa wrote, **July in my hometown is when green grapes ripen**.', ja: '李陸史は、**わがふるさとの七月は青葡萄の熟れるころ**と書きました。', es: 'Yi Yuksa escribió: **julio en mi tierra es cuando maduran las uvas verdes**.', fr: 'Yi Yuksa a écrit : **juillet, chez moi, c’est la saison où mûrit le raisin vert**.' },
  // ── 김영랑 (1903–1950)
  { s: 'spring', w: 'clear', ko: '김영랑은 **돌담에 속삭이는 햇발**처럼 마음이 고요하길 바랐어요.', en: 'Kim Yeong-rang wished his heart could be as calm as **sunlight whispering on a stone wall**.', ja: '金永郎は、**石垣にささやく日ざし**のように心が静かであればと願いました。', es: 'Kim Yeong-rang deseaba un corazón tranquilo como **el sol que susurra sobre un muro de piedra**.', fr: 'Kim Yeong-rang voulait un cœur calme comme **le soleil qui murmure sur un mur de pierre**.' },
  { s: 'spring', ko: '김영랑은 **모란이 피기까지는 아직 나의 봄을 기다린다**고 했어요.', en: 'Kim Yeong-rang said that **until the peonies bloom, he is still waiting for his spring**.', ja: '金永郎は、**牡丹が咲くまでは、まだわたしの春を待っている**と書きました。', es: 'Kim Yeong-rang dijo que **hasta que florezcan las peonías, sigue esperando su primavera**.', fr: 'Kim Yeong-rang disait **attendre encore son printemps, jusqu’à ce que fleurissent les pivoines**.' },
  { s: 'autumn', ko: '김영랑은 붉은 잎을 보고 **오매, 단풍 들겄네**라고 했어요.', en: 'Seeing red leaves, Kim Yeong-rang cried, **oh my, the leaves are turning**.', ja: '金永郎は赤い葉を見て、**あらまあ、紅葉しそうだね**と言いました。', es: 'Al ver las hojas rojas, Kim Yeong-rang exclamó: **¡ay, ya se tiñen las hojas!**', fr: 'Voyant les feuilles rouges, Kim Yeong-rang s’écria : **oh, les feuilles vont rougir !**' },
  // ── 이상화 (1901–1943)
  { s: 'spring', w: 'clear', ko: '이상화는 **푸른 하늘 푸른 들이 맞붙은 곳으로** 꿈속을 가듯 걸었다고 썼어요.', en: 'Yi Sang-hwa walked as in a dream **toward where the blue sky meets the green fields**.', ja: '李相和は、**青い空と青い野が触れあうところへ**夢の中を行くように歩いたと書きました。', es: 'Yi Sang-hwa caminó como en un sueño **hacia donde el cielo azul toca los campos verdes**.', fr: 'Yi Sang-hwa marchait comme en rêve **vers l’endroit où le ciel bleu touche les champs verts**.' },
  // ── 황진이 (16세기)
  { s: 'winter', t: 'night', ko: '황진이는 **동짓달 기나긴 밤의 한 허리를 베어 내어** 두고 싶다고 했어요.', en: 'Hwang Jini wished to **cut a piece from the long midwinter night** and keep it for later.', ja: '黄真伊は、**冬至の長い夜のひと腰を切り取って**しまっておきたいと詠みました。', es: 'Hwang Jini quería **cortar un trozo de la larga noche de invierno** y guardarlo.', fr: 'Hwang Jini voulait **couper un morceau de la longue nuit d’hiver** pour le garder.' },
  // ── 당시(唐詩)
  { t: 'night', ko: '이백은 **침상 앞의 달빛이 땅 위의 서리인가** 싶었다고 썼어요.', en: 'Li Bai wrote that **the moonlight before his bed looked like frost on the ground**.', ja: '李白は、**床の前の月光を地上の霜かと思った**と詠みました。', es: 'Li Bai escribió que **la luz de luna ante su cama parecía escarcha en el suelo**.', fr: 'Li Bai a écrit que **le clair de lune devant son lit ressemblait à du givre**.' },
  { w: 'rain', ko: '두보는 **좋은 비는 때를 안다**고 썼어요.', en: 'Du Fu wrote that **a good rain knows its season**.', ja: '杜甫は、**よい雨は時節を知る**と詠みました。', es: 'Du Fu escribió que **la buena lluvia conoce su momento**.', fr: 'Du Fu a écrit que **la bonne pluie connaît sa saison**.' },
  { s: 'spring', t: 'morning', ko: '맹호연은 **봄잠에 새벽인 줄 몰랐는데 곳곳에서 새소리가 들린다**고 썼어요.', en: 'Meng Haoran wrote, **spring sleep knows no dawn, and birds are singing everywhere**.', ja: '孟浩然は、**春眠暁を覚えず、処処に啼鳥を聞く**と詠みました。', es: 'Meng Haoran escribió: **el sueño de primavera no siente el alba, y en todas partes cantan los pájaros**.', fr: 'Meng Haoran a écrit : **le sommeil du printemps ignore l’aube, partout chantent les oiseaux**.' },
  { t: 'day', ko: '왕유는 **빈 산에 사람은 보이지 않고 말소리만 들린다**고 썼어요.', en: 'Wang Wei wrote, **on the empty mountain no one is seen, only voices are heard**.', ja: '王維は、**空山に人を見ず、ただ人語の響きを聞く**と詠みました。', es: 'Wang Wei escribió: **en la montaña vacía no se ve a nadie, solo se oyen voces**.', fr: 'Wang Wei a écrit : **sur la montagne vide, personne, seulement des voix**.' },
  // ── 하이쿠
  { s: 'spring', ko: '바쇼는 **오래된 연못, 개구리 뛰어드는 물소리**를 들었어요.', en: 'Bashō heard **an old pond, a frog jumping in, the sound of water**.', ja: '芭蕉は、**古池や蛙飛び込む水の音**と詠みました。', es: 'Bashō oyó **un viejo estanque, una rana que salta, el sonido del agua**.', fr: 'Bashō entendit **un vieil étang, une grenouille qui plonge, le bruit de l’eau**.' },
  { s: 'summer', ko: '바쇼는 **바위에 스며드는 매미 소리** 속에서 고요를 찾았어요.', en: 'Bashō found stillness in **the cicadas’ voices seeping into the rocks**.', ja: '芭蕉は、**閑さや岩にしみ入る蝉の声**と詠みました。', es: 'Bashō halló la calma en **el canto de las cigarras que se filtra en las rocas**.', fr: 'Bashō trouva le calme dans **le chant des cigales qui pénètre les rochers**.' },
  { s: 'summer', t: 'night', ko: '바쇼는 **거친 바다 위로 비스듬히 누운 은하수**를 보았어요.', en: 'Bashō saw **the Milky Way lying across the rough sea**.', ja: '芭蕉は、**荒海や佐渡によこたふ天河**と詠みました。', es: 'Bashō vio **la Vía Láctea tendida sobre el mar bravo**.', fr: 'Bashō vit **la Voie lactée couchée sur la mer agitée**.' },
  { s: 'spring', ko: '잇사는 **눈이 녹으니 마을 가득 아이들**이라고 읊었어요.', en: 'Issa wrote, **the snow has melted, and the village is full of children**.', ja: '一茶は、**雪とけて村いっぱいの子どもかな**と詠みました。', es: 'Issa escribió: **se derritió la nieve, y el pueblo está lleno de niños**.', fr: 'Issa a écrit : **la neige a fondu, le village est plein d’enfants**.' },
  { s: 'spring', t: 'evening', ko: '부손은 **유채꽃, 달은 동쪽에 해는 서쪽에**라고 읊었어요.', en: 'Buson wrote, **rapeseed flowers, the moon in the east, the sun in the west**.', ja: '蕪村は、**菜の花や月は東に日は西に**と詠みました。', es: 'Buson escribió: **flores de colza, la luna al este, el sol al oeste**.', fr: 'Buson a écrit : **fleurs de colza, la lune à l’est, le soleil à l’ouest**.' },
  { s: 'spring', ko: '부손은 **봄 바다는 종일 느릿느릿 출렁인다**고 읊었어요.', en: 'Buson wrote, **the spring sea rises and falls, slowly, all day long**.', ja: '蕪村は、**春の海終日のたりのたりかな**と詠みました。', es: 'Buson escribió: **el mar de primavera sube y baja despacio todo el día**.', fr: 'Buson a écrit : **la mer de printemps ondule lentement tout le jour**.' },
  { s: 'autumn', ko: '시키는 **감을 먹으니 호류지 종이 울린다**고 읊었어요.', en: 'Shiki wrote, **I bite a persimmon, and the bell of Hōryū-ji rings**.', ja: '子規は、**柿食へば鐘が鳴るなり法隆寺**と詠みました。', es: 'Shiki escribió: **muerdo un caqui y suena la campana de Hōryū-ji**.', fr: 'Shiki a écrit : **je croque un kaki, la cloche du Hōryū-ji résonne**.' },
  { s: 'spring', t: 'night', ko: '요사노 아키코는 벚꽃 달밤에 **오늘 밤 만나는 사람 모두 아름답다**고 했어요.', en: 'On a cherry-blossom moonlit night, Yosano Akiko wrote that **everyone I meet tonight is beautiful**.', ja: '与謝野晶子は桜月夜に、**今宵逢ふ人みなうつくしき**と詠みました。', es: 'En una noche de luna y cerezos, Yosano Akiko escribió que **todos los que encuentro esta noche son hermosos**.', fr: 'Une nuit de lune et de cerisiers, Yosano Akiko écrivit que **tous ceux que je croise ce soir sont beaux**.' },
  // ── 나쓰메 소세키 (1867–1916)
  { t: 'day', ko: '나쓰메 소세키의 소설은 **산길을 오르며 이렇게 생각했다**로 시작해요.', en: 'A Natsume Sōseki novel opens with **climbing a mountain path, I thought this**.', ja: '夏目漱石の小説は、**山路を登りながら、こう考えた**で始まります。', es: 'Una novela de Natsume Sōseki empieza así: **subiendo por un sendero de montaña, pensé esto**.', fr: 'Un roman de Natsume Sōseki commence ainsi : **en gravissant un sentier de montagne, je pensais ceci**.' },
  { t: 'night', ko: '소세키는 **백 년은 벌써 와 있었구나** 하고 깨닫는 꿈을 썼어요.', en: 'Sōseki wrote of a dream in which one realises, **the hundred years had already come**.', ja: '漱石は、**百年はもう来ていたんだな**と気づく夢を書きました。', es: 'Sōseki escribió un sueño en el que uno comprende: **los cien años ya habían llegado**.', fr: 'Sōseki a écrit un rêve où l’on comprend : **les cent ans étaient déjà venus**.' },
  // ── 미야자와 겐지 (1896–1933)
  { w: 'rain', ko: '미야자와 겐지는 **비에도 지지 않고, 바람에도 지지 않고**라고 썼어요.', en: 'Miyazawa Kenji wrote, **not beaten by the rain, not beaten by the wind**.', ja: '宮沢賢治は、**雨ニモマケズ、風ニモマケズ**と書きました。', es: 'Miyazawa Kenji escribió: **sin rendirse a la lluvia, sin rendirse al viento**.', fr: 'Miyazawa Kenji a écrit : **ne pas céder à la pluie, ne pas céder au vent**.' },
  { t: 'night', w: 'clear', ko: '미야자와 겐지는 은하를 건너는 기차에서 **어디까지나 같이 가자**고 썼어요.', en: 'On a train across the Milky Way, Miyazawa Kenji wrote, **let’s go together, as far as we can**.', ja: '宮沢賢治は銀河を渡る汽車で、**どこまでもどこまでも一緒に行こう**と書きました。', es: 'En un tren que cruza la Vía Láctea, Miyazawa Kenji escribió: **vayamos juntos, tan lejos como podamos**.', fr: 'Dans un train traversant la Voie lactée, Miyazawa Kenji a écrit : **allons ensemble, aussi loin que possible**.' },
  // ── 아쿠타가와 류노스케 (1892–1927)
  { t: 'evening', s: 'winter', ko: '아쿠타가와는 해 질 녘 기차 창밖으로 **흩날리는 선명한 귤빛**을 보았어요.', en: 'At dusk, from a train window, Akutagawa saw **the bright colour of tangerines falling through the air**.', ja: '芥川は夕暮れの汽車の窓から、**乱落する鮮な蜜柑の色**を見ました。', es: 'Al atardecer, desde la ventana de un tren, Akutagawa vio **el color vivo de unas mandarinas cayendo por el aire**.', fr: 'Au crépuscule, d’une fenêtre de train, Akutagawa vit **la couleur vive de mandarines tombant dans l’air**.' },
  // ── 헨리 데이비드 소로 (1817–1862)
  { w: 'clear', ko: '소로는 **하늘은 머리 위에만이 아니라 발아래에도 있다**고 썼어요.', en: 'Thoreau wrote that **heaven is under our feet as well as over our heads**.', ja: 'ソローは、**天は頭上だけでなく足もとにもある**と書きました。', es: 'Thoreau escribió que **el cielo está bajo nuestros pies tanto como sobre nuestras cabezas**.', fr: 'Thoreau a écrit que **le ciel est sous nos pieds autant qu’au-dessus de nos têtes**.' },
  { ko: '소로는 **계절이 지나는 대로 그 계절을 살라**고 했어요.', en: 'Thoreau said to **live in each season as it passes**.', ja: 'ソローは、**過ぎゆく季節をそのたびに生きよ**と言いました。', es: 'Thoreau decía que hay que **vivir cada estación mientras pasa**.', fr: 'Thoreau disait de **vivre chaque saison à mesure qu’elle passe**.' },
  { t: 'morning', ko: '소로는 **아침이란 내가 깨어 있고 내 안에 새벽이 있을 때**라고 썼어요.', en: 'Thoreau wrote, **morning is when I am awake and there is a dawn in me**.', ja: 'ソローは、**朝とは、私が目覚め、私の中に夜明けがあるとき**と書きました。', es: 'Thoreau escribió: **la mañana es cuando estoy despierto y hay un amanecer en mí**.', fr: 'Thoreau a écrit : **le matin, c’est quand je suis éveillé et qu’il y a une aube en moi**.' },
  // ── 버지니아 울프 (1882–1941)
  { t: 'morning', ko: '버지니아 울프의 『파도』는 **해는 아직 뜨지 않았다**로 시작해요.', en: 'Virginia Woolf’s The Waves begins, **the sun had not yet risen**.', ja: 'ヴァージニア・ウルフの『波』は、**日はまだ昇っていなかった**で始まります。', es: 'Las olas, de Virginia Woolf, empieza así: **el sol aún no había salido**.', fr: 'Les Vagues, de Virginia Woolf, commence ainsi : **le soleil ne s’était pas encore levé**.' },
  { t: 'morning', ko: '버지니아 울프는 아침 공기를 두고 **이 얼마나 신나는지, 이 얼마나 뛰어드는 기분인지**라고 썼어요.', en: 'Of the morning air, Virginia Woolf wrote, **what a lark! what a plunge!**', ja: 'ヴァージニア・ウルフは朝の空気を、**なんて愉快、なんて飛びこむような気分**と書きました。', es: 'Sobre el aire de la mañana, Virginia Woolf escribió: **¡qué alegría! ¡qué zambullida!**', fr: 'De l’air du matin, Virginia Woolf a écrit : **quelle joie ! quel plongeon !**' },
  { t: 'morning', ko: '울프의 댈러웨이 부인은 **꽃은 자기가 사 오겠다**고 말하며 하루를 시작해요.', en: 'Woolf’s Mrs Dalloway starts her day saying **she would buy the flowers herself**.', ja: 'ウルフのダロウェイ夫人は、**花は自分で買ってくる**と言って一日を始めます。', es: 'La señora Dalloway de Woolf empieza el día diciendo que **ella misma comprará las flores**.', fr: 'Mrs Dalloway, chez Woolf, commence sa journée en disant qu’**elle achèterait les fleurs elle-même**.' },
  { ko: '울프의 소설에서 램지 부인은 **내일 날씨만 좋다면 물론이지**라고 말해요.', en: 'In Woolf’s novel, Mrs Ramsay says, **yes, of course, if it’s fine tomorrow**.', ja: 'ウルフの小説で、ラムジー夫人は**ええ、もちろん、明日晴れたらね**と言います。', es: 'En la novela de Woolf, la señora Ramsay dice: **sí, claro, si mañana hace buen tiempo**.', fr: 'Dans le roman de Woolf, Mrs Ramsay dit : **oui, bien sûr, s’il fait beau demain**.' },
  // ── F. 스콧 피츠제럴드 (1896–1940)
  { s: 'summer', ko: '피츠제럴드는 **여름과 함께 삶이 다시 시작된다**는 익숙한 확신을 썼어요.', en: 'Fitzgerald wrote of the familiar conviction that **life was beginning over again with the summer**.', ja: 'フィッツジェラルドは、**夏とともに人生がまた始まる**というおなじみの確信を書きました。', es: 'Fitzgerald escribió la conocida certeza de que **la vida volvía a empezar con el verano**.', fr: 'Fitzgerald a écrit cette conviction familière que **la vie recommençait avec l’été**.' },
  { s: 'summer', t: 'night', ko: '피츠제럴드는 여름밤 정원의 사람들을 **속삭임과 샴페인과 별 사이를 오가는 나방** 같다고 썼어요.', en: 'Fitzgerald saw people in a summer garden coming and going **like moths among the whisperings and the champagne and the stars**.', ja: 'フィッツジェラルドは夏の夜の庭の人々を、**ささやきとシャンパンと星のあいだを行き交う蛾**のようだと書きました。', es: 'Fitzgerald vio a la gente de un jardín de verano ir y venir **como polillas entre susurros, champán y estrellas**.', fr: 'Fitzgerald voyait les gens d’un jardin d’été aller et venir **comme des papillons de nuit parmi les murmures, le champagne et les étoiles**.' },
  // ── 캐서린 맨스필드 (1888–1923)
  { w: 'clear', ko: '맨스필드의 「가든파티」는 **결국 날씨는 더할 나위 없었다**로 시작해요.', en: 'Mansfield’s The Garden Party begins, **and after all the weather was ideal**.', ja: 'マンスフィールドの「園遊会」は、**結局、天気は申し分なかった**で始まります。', es: 'La fiesta en el jardín, de Mansfield, empieza así: **y al final el tiempo fue perfecto**.', fr: 'La Garden-party, de Mansfield, commence ainsi : **et finalement le temps était idéal**.' },
  { t: 'morning', ko: '맨스필드는 서른이 되어도 **걷는 대신 뛰고 싶은 순간**이 있다고 썼어요.', en: 'Mansfield wrote that even at thirty there are **moments when you want to run instead of walk**.', ja: 'マンスフィールドは、三十歳になっても**歩くかわりに走りたくなる瞬間**があると書きました。', es: 'Mansfield escribió que, aun a los treinta, hay **momentos en que uno quiere correr en vez de caminar**.', fr: 'Mansfield a écrit qu’à trente ans encore il y a **des moments où l’on veut courir au lieu de marcher**.' },
  // ── 에밀리 디킨슨 (1830–1886)
  { w: 'cloud', ko: '디킨슨은 **희망은 깃털 달린 것**이라고 썼어요.', en: 'Dickinson wrote that **hope is the thing with feathers**.', ja: 'ディキンソンは、**希望とは羽根のあるもの**と書きました。', es: 'Dickinson escribió que **la esperanza es esa cosa con plumas**.', fr: 'Dickinson a écrit que **l’espoir est cette chose à plumes**.' },
  { s: 'winter', t: 'day', ko: '디킨슨은 **겨울 오후에 비스듬히 드는 빛**을 노래했어요.', en: 'Dickinson wrote of **a certain slant of light on winter afternoons**.', ja: 'ディキンソンは、**冬の午後に斜めにさす光**を詠いました。', es: 'Dickinson escribió sobre **cierta luz oblicua en las tardes de invierno**.', fr: 'Dickinson a écrit sur **une certaine lumière oblique des après-midi d’hiver**.' },
  // ── 영국 시인
  { s: 'autumn', ko: '키츠는 가을을 **안개와 무르익은 결실의 계절**이라고 불렀어요.', en: 'Keats called autumn the **season of mists and mellow fruitfulness**.', ja: 'キーツは秋を、**霧と、熟れた実りの季節**と呼びました。', es: 'Keats llamó al otoño **estación de brumas y frutos maduros**.', fr: 'Keats appelait l’automne la **saison des brumes et des fruits mûrs**.' },
  { s: 'spring', ko: '워즈워스는 **구름처럼 홀로 거닐다 금빛 수선화 무리**를 만났어요.', en: 'Wordsworth **wandered lonely as a cloud** and found a host of golden daffodils.', ja: 'ワーズワースは**雲のようにひとりさまよい**、金色の水仙の群れに出会いました。', es: 'Wordsworth **vagaba solo como una nube** y encontró un mar de narcisos dorados.', fr: 'Wordsworth **errait solitaire comme un nuage** et trouva une foule de jonquilles dorées.' },
  { s: 'winter', ko: '셸리는 **겨울이 오면 봄도 멀지 않으리**라고 썼어요.', en: 'Shelley wrote, **if winter comes, can spring be far behind?**', ja: 'シェリーは、**冬来たりなば春遠からじ**と書きました。', es: 'Shelley escribió: **si llega el invierno, ¿puede estar lejos la primavera?**', fr: 'Shelley a écrit : **si l’hiver vient, le printemps peut-il être loin ?**' },
  { w: 'cloud', ko: '크리스티나 로세티는 **누가 바람을 보았나요, 나도 너도 못 보았지**라고 썼어요.', en: 'Christina Rossetti wrote, **who has seen the wind? neither I nor you**.', ja: 'クリスティナ・ロセッティは、**だれが風を見たでしょう、わたしもあなたも見はしない**と書きました。', es: 'Christina Rossetti escribió: **¿quién ha visto el viento? ni tú ni yo**.', fr: 'Christina Rossetti a écrit : **qui a vu le vent ? ni toi ni moi**.' },
  { s: 'winter', w: 'snow', ko: '로세티는 **혹독한 한겨울, 서리 바람이 신음했다**고 썼어요.', en: 'Rossetti wrote, **in the bleak midwinter, frosty wind made moan**.', ja: 'ロセッティは、**厳しい真冬、霜の風がうめいた**と書きました。', es: 'Rossetti escribió: **en el crudo invierno, gemía el viento helado**.', fr: 'Rossetti a écrit : **au cœur de l’âpre hiver, le vent glacé gémissait**.' },
  { t: 'day', ko: '예이츠는 호숫가에서 **평화는 천천히 방울져 내린다**고 썼어요.', en: 'By the lake, Yeats wrote that **peace comes dropping slow**.', ja: 'イェイツは湖のほとりで、**平和はゆっくりと滴り落ちてくる**と書きました。', es: 'Junto al lago, Yeats escribió que **la paz llega goteando despacio**.', fr: 'Au bord du lac, Yeats a écrit que **la paix vient goutte à goutte, lentement**.' },
  { s: 'spring', ko: '예이츠는 **나무에 잎이 자라듯 삶을 쉽게 받아들이라**는 말을 들었어요.', en: 'Yeats was told to **take life easy, as the leaves grow on the tree**.', ja: 'イェイツは、**木に葉が育つように、気楽に生きなさい**と言われました。', es: 'A Yeats le dijeron que **se tomara la vida con calma, como crecen las hojas en el árbol**.', fr: 'On dit à Yeats de **prendre la vie doucement, comme poussent les feuilles sur l’arbre**.' },
  { t: 'night', ko: '예이츠는 **내 꿈 위를 걸으니 사뿐히 걸어 달라**고 했어요.', en: 'Yeats asked, **tread softly because you tread on my dreams**.', ja: 'イェイツは、**そっと歩いて、あなたは私の夢の上を歩くのだから**と書きました。', es: 'Yeats pidió: **pisa suavemente, porque pisas mis sueños**.', fr: 'Yeats demandait : **marche doucement, car tu marches sur mes rêves**.' },
  // ── 어린 시절의 책들
  { s: 'autumn', ko: '『빨간 머리 앤』의 앤은 **10월이 있는 세상에 살아서 참 기쁘다**고 했어요.', en: 'Anne of Green Gables said, **I’m so glad I live in a world where there are Octobers**.', ja: '『赤毛のアン』のアンは、**十月のある世界に生きていてうれしい**と言いました。', es: 'Ana, la de Tejas Verdes, dijo: **me alegra tanto vivir en un mundo donde hay octubres**.', fr: 'Anne, la maison aux pignons verts, disait : **je suis si contente de vivre dans un monde où il y a des octobres**.' },
  { t: 'morning', ko: '앤은 **내일은 아직 아무 실수도 없는 새날**이라고 했어요.', en: 'Anne said, **tomorrow is always fresh, with no mistakes in it yet**.', ja: 'アンは、**明日はいつも新しくて、まだ何の失敗もない**と言いました。', es: 'Ana dijo: **mañana siempre es nuevo, todavía sin errores**.', fr: 'Anne disait : **demain est toujours neuf, sans aucune erreur encore**.' },
  { w: 'clear', ko: '앤은 **사랑스러운 세상아, 네 안에 살아 있어 기쁘다**고 했어요.', en: 'Anne said, **dear old world, you are very lovely, and I am glad to be alive in you**.', ja: 'アンは、**なつかしい世界、あなたはとても美しい、あなたの中で生きていてうれしい**と言いました。', es: 'Ana dijo: **querido mundo, eres precioso, y me alegra estar viva en ti**.', fr: 'Anne disait : **cher vieux monde, tu es si beau, et je suis heureuse d’être vivante en toi**.' },
  { s: 'spring', ko: '『비밀의 화원』에는 **제대로 바라보면 온 세상이 정원**이라는 말이 나와요.', en: 'In The Secret Garden: **if you look the right way, you can see that the whole world is a garden**.', ja: '『秘密の花園』には、**ちゃんと見れば、世界じゅうが庭なのよ**という言葉があります。', es: 'En El jardín secreto se dice que **si miras bien, verás que el mundo entero es un jardín**.', fr: 'Dans Le Jardin secret : **si l’on regarde bien, le monde entier est un jardin**.' },
  { s: 'spring', t: 'morning', ko: '『버드나무에 부는 바람』의 두더지는 **아침 내내 봄맞이 대청소**를 했어요.', en: 'In The Wind in the Willows, the Mole **had been spring-cleaning his little home all morning**.', ja: '『たのしい川べ』のモグラは、**朝からずっと春の大掃除**をしていました。', es: 'En El viento en los sauces, el Topo **pasó toda la mañana haciendo limpieza de primavera**.', fr: 'Dans Le Vent dans les saules, la Taupe **avait fait le ménage de printemps toute la matinée**.' },
  { s: 'summer', ko: '『버드나무에 부는 바람』에는 **그냥 배를 타고 노니는 것만큼 좋은 일은 없다**는 말이 나와요.', en: 'The Wind in the Willows says **there is nothing half so much worth doing as simply messing about in boats**.', ja: '『たのしい川べ』には、**ただボートでぶらぶらすることほどすてきなことはない**という言葉があります。', es: 'En El viento en los sauces se dice que **nada vale tanto la pena como pasear sin rumbo en barca**.', fr: 'Le Vent dans les saules dit qu’**il n’y a rien de mieux que de flâner en bateau**.' },
  { t: 'night', ko: '피터 팬은 네버랜드 가는 길을 **오른쪽 두 번째, 그리고 아침까지 곧장**이라고 했어요.', en: 'Peter Pan gave the way to Neverland: **second to the right, and then straight on till morning**.', ja: 'ピーター・パンはネバーランドへの道を、**右から二番目、そこから朝までまっすぐ**と言いました。', es: 'Peter Pan indicó el camino a Nunca Jamás: **la segunda a la derecha, y luego todo recto hasta el amanecer**.', fr: 'Peter Pan indiquait le chemin du Pays imaginaire : **la deuxième à droite, puis tout droit jusqu’au matin**.' },
  { ko: '앨리스는 **어제로 돌아가 봐야 소용없다, 그때의 나는 다른 사람이었으니까**라고 했어요.', en: 'Alice said, **it’s no use going back to yesterday, because I was a different person then**.', ja: 'アリスは、**昨日に戻っても意味がない、あのときの私は別人だったから**と言いました。', es: 'Alicia dijo: **no sirve de nada volver a ayer, porque entonces era otra persona**.', fr: 'Alice disait : **inutile de revenir à hier, j’étais une autre personne alors**.' },
  { t: 'morning', w: 'clear', ko: '마크 트웨인은 **고요한 세상 위로 해가 떠 축복처럼 마을을 비췄다**고 썼어요.', en: 'Mark Twain wrote that **the sun rose upon a tranquil world, and beamed down upon the peaceful village like a benediction**.', ja: 'マーク・トウェインは、**静かな世界に日が昇り、祝福のように村を照らした**と書きました。', es: 'Mark Twain escribió que **el sol salió sobre un mundo tranquilo y bañó el pueblo como una bendición**.', fr: 'Mark Twain a écrit que **le soleil se leva sur un monde paisible et baigna le village comme une bénédiction**.' },
  { w: 'rain', ko: '『작은 아씨들』의 에이미는 **폭풍이 두렵지 않다, 배 모는 법을 배우는 중이니까**라고 했어요.', en: 'In Little Women, Amy says, **I’m not afraid of storms, for I’m learning how to sail my ship**.', ja: '『若草物語』のエイミーは、**嵐はこわくない、船の操り方を学んでいるから**と言いました。', es: 'En Mujercitas, Amy dice: **no temo a las tormentas, porque estoy aprendiendo a llevar mi barco**.', fr: 'Dans Les Quatre Filles du docteur March, Amy dit : **je n’ai pas peur des tempêtes, j’apprends à mener mon navire**.' },
  { s: 'summer', w: 'clear', ko: '제인 오스틴은 **맑은 날 그늘에 앉아 초록을 바라보는 것**이 가장 좋은 휴식이라고 썼어요.', en: 'Jane Austen wrote that **to sit in the shade on a fine day, and look upon verdure**, is the most perfect refreshment.', ja: 'ジェイン・オースティンは、**晴れた日に木陰に座って緑をながめること**が何よりの休息だと書きました。', es: 'Jane Austen escribió que **sentarse a la sombra en un día bueno y mirar el verdor** es el descanso perfecto.', fr: 'Jane Austen a écrit que **s’asseoir à l’ombre par beau temps et regarder la verdure** est le repos parfait.' },
  // ── 그 밖의 문학
  { ko: '휘트먼은 **빛과 어둠의 모든 시간이 기적**이라고 썼어요.', en: 'Whitman wrote, **to me every hour of the light and dark is a miracle**.', ja: 'ホイットマンは、**光と闇のどの時間も奇跡だ**と書きました。', es: 'Whitman escribió: **para mí, cada hora de luz y de oscuridad es un milagro**.', fr: 'Whitman a écrit : **pour moi, chaque heure de lumière et d’ombre est un miracle**.' },
  { t: 'night', ko: '오스카 와일드는 **우리 중 누군가는 별을 바라보고 있다**고 썼어요.', en: 'Oscar Wilde wrote that **some of us are looking at the stars**.', ja: 'オスカー・ワイルドは、**私たちのうち誰かは星を見上げている**と書きました。', es: 'Oscar Wilde escribió que **algunos de nosotros estamos mirando las estrellas**.', fr: 'Oscar Wilde a écrit que **certains d’entre nous regardent les étoiles**.' },
  { t: 'day', ko: '프루스트는 **홍차에 적신 마들렌 한 조각**에서 지난날이 되살아났다고 썼어요.', en: 'Proust wrote that the past came back from **a piece of madeleine dipped in tea**.', ja: 'プルーストは、**紅茶にひたしたマドレーヌのひとかけら**から過ぎた日がよみがえったと書きました。', es: 'Proust escribió que el pasado volvió con **un trozo de magdalena mojado en té**.', fr: 'Proust a écrit que le passé revint avec **un morceau de madeleine trempé dans le thé**.' },
  { s: 'spring', w: 'clear', ko: '괴테는 **레몬꽃 피는 그 나라를 아느냐**고 노래했어요.', en: 'Goethe sang, **do you know the land where the lemon trees bloom?**', ja: 'ゲーテは、**レモンの花咲く国を知っているか**と歌いました。', es: 'Goethe cantó: **¿conoces el país donde florecen los limoneros?**', fr: 'Goethe chantait : **connais-tu le pays où fleurissent les citronniers ?**' },
  { s: 'spring', ko: '하이네는 **눈부시게 아름다운 오월에**라고 노래했어요.', en: 'Heine sang of **the wondrous lovely month of May**.', ja: 'ハイネは、**うるわしい五月に**と歌いました。', es: 'Heine cantó al **maravilloso mes de mayo**.', fr: 'Heine chantait **le merveilleux mois de mai**.' },
  { s: 'winter', w: 'clear', t: 'morning', ko: '푸시킨은 **서리와 햇살, 참 멋진 날**이라고 썼어요.', en: 'Pushkin wrote, **frost and sunshine, a wonderful day**.', ja: 'プーシキンは、**霜と陽ざし、すばらしい日**と書きました。', es: 'Pushkin escribió: **helada y sol, un día maravilloso**.', fr: 'Pouchkine a écrit : **gel et soleil, quelle merveilleuse journée**.' },
  { w: 'rain', ko: '베를렌은 **도시에 비가 내리듯 내 마음에 눈물이 내린다**고 썼어요.', en: 'Verlaine wrote, **it weeps in my heart as it rains on the town**.', ja: 'ヴェルレーヌは、**町に雨が降るように、わたしの心に涙が降る**と書きました。', es: 'Verlaine escribió: **llora en mi corazón como llueve sobre la ciudad**.', fr: 'Verlaine a écrit : **il pleure dans mon cœur comme il pleut sur la ville**.' },
  { s: 'autumn', ko: '베를렌은 **가을 바이올린의 긴 흐느낌**을 노래했어요.', en: 'Verlaine wrote of **the long sobs of the violins of autumn**.', ja: 'ヴェルレーヌは、**秋のヴァイオリンの長いすすり泣き**を歌いました。', es: 'Verlaine escribió sobre **los largos sollozos de los violines del otoño**.', fr: 'Verlaine chantait **les sanglots longs des violons de l’automne**.' },
  { t: 'evening', ko: '아폴리네르는 **밤이 오고 종이 울려도, 날들은 가고 나는 남는다**고 썼어요.', en: 'Apollinaire wrote, **let night come, let the hour strike, the days go by, I remain**.', ja: 'アポリネールは、**夜よ来い、鐘よ鳴れ、日々は去り、わたしは残る**と書きました。', es: 'Apollinaire escribió: **que venga la noche, que suene la hora, los días se van y yo me quedo**.', fr: 'Apollinaire a écrit : **vienne la nuit sonne l’heure, les jours s’en vont je demeure**.' },
  { s: 'spring', ko: '베케르는 **어두운 제비들이 다시 돌아오리라**고 썼어요.', en: 'Bécquer wrote, **the dark swallows will return**.', ja: 'ベッケルは、**黒いつばめはまた戻ってくるだろう**と書きました。', es: 'Bécquer escribió: **volverán las oscuras golondrinas**.', fr: 'Bécquer a écrit : **les sombres hirondelles reviendront**.' },
  { t: 'day', ko: '마차도는 **길은 걸어가면서 만들어진다**고 썼어요.', en: 'Machado wrote that **the path is made by walking**.', ja: 'マチャードは、**道は歩くことでつくられる**と書きました。', es: 'Machado escribió: **se hace camino al andar**.', fr: 'Machado a écrit que **le chemin se fait en marchant**.' },
  { s: 'summer', ko: '로르카는 **초록, 너를 사랑해 초록**이라고 노래했어요.', en: 'Lorca sang, **green, how I love you, green**.', ja: 'ロルカは、**緑、きみを愛している緑**と歌いました。', es: 'Lorca cantó: **verde que te quiero verde**.', fr: 'Lorca chantait : **vert, je t’aime vert**.' },
  { w: 'cloud', t: 'evening', ko: '타고르는 구름이 이제 **내 노을 하늘에 빛깔을 더하러** 온다고 썼어요.', en: 'Tagore wrote that clouds now come **to add colour to my sunset sky**.', ja: 'タゴールは、雲はいま**わたしの夕焼け空に色をそえに**来ると書きました。', es: 'Tagore escribió que las nubes vienen ahora **a dar color a mi cielo de atardecer**.', fr: 'Tagore a écrit que les nuages viennent maintenant **ajouter de la couleur à mon ciel de couchant**.' },
  { ko: '타고르는 **나비는 달이 아니라 순간을 세기에 시간이 넉넉하다**고 썼어요.', en: 'Tagore wrote, **the butterfly counts not months but moments, and has time enough**.', ja: 'タゴールは、**蝶は月ではなく瞬間を数えるから、時間は十分にある**と書きました。', es: 'Tagore escribió: **la mariposa no cuenta meses sino momentos, y le sobra el tiempo**.', fr: 'Tagore a écrit : **le papillon compte non les mois mais les instants, et il a assez de temps**.' },
  { t: 'night', ko: '타고르는 **해를 그리워하며 울면 별도 놓친다**고 썼어요.', en: 'Tagore wrote, **if you shed tears when you miss the sun, you also miss the stars**.', ja: 'タゴールは、**太陽を恋しがって泣けば、星も見逃してしまう**と書きました。', es: 'Tagore escribió: **si lloras por haber perdido el sol, tampoco verás las estrellas**.', fr: 'Tagore a écrit : **si tu pleures d’avoir manqué le soleil, tu manqueras aussi les étoiles**.' },
  { s: 'summer', w: 'clear', ko: '칼릴 지브란은 **땅은 맨발을 반기고 바람은 머리카락과 놀고 싶어 한다**고 썼어요.', en: 'Kahlil Gibran wrote that **the earth delights to feel your bare feet and the winds long to play with your hair**.', ja: 'ジブランは、**大地は素足を喜び、風は髪とたわむれたがっている**と書きました。', es: 'Gibran escribió que **la tierra disfruta de tus pies descalzos y el viento quiere jugar con tu pelo**.', fr: 'Gibran a écrit que **la terre aime sentir tes pieds nus et le vent veut jouer avec tes cheveux**.' },
  { s: 'winter', t: 'morning', ko: '『작은 아씨들』은 **선물 없는 크리스마스는 크리스마스가 아니야**라는 투정으로 시작해요.', en: 'Little Women begins with a grumble: **Christmas won’t be Christmas without any presents**.', ja: '『若草物語』は、**プレゼントのないクリスマスなんてクリスマスじゃない**というぼやきで始まります。', es: 'Mujercitas empieza con una queja: **la Navidad no será Navidad sin regalos**.', fr: 'Les Quatre Filles du docteur March commence par une plainte : **Noël ne sera pas Noël sans cadeaux**.' },
  { ko: '스티븐슨은 **세상은 온갖 것으로 가득하니 우리 모두 왕처럼 행복할 거야**라고 썼어요.', en: 'Stevenson wrote, **the world is so full of a number of things, I’m sure we should all be as happy as kings**.', ja: 'スティーヴンソンは、**世界はいろんなものでいっぱいだから、みんな王さまみたいに幸せになれる**と書きました。', es: 'Stevenson escribió: **el mundo está tan lleno de cosas que todos deberíamos ser felices como reyes**.', fr: 'Stevenson a écrit : **le monde est si plein de choses que nous devrions tous être heureux comme des rois**.' },
  { t: 'day', w: 'clear', ko: '스티븐슨은 **나와 함께 들락날락하는 작은 그림자**를 노래했어요.', en: 'Stevenson wrote of **a little shadow that goes in and out with me**.', ja: 'スティーヴンソンは、**わたしといっしょに出たり入ったりする小さな影**を歌いました。', es: 'Stevenson escribió sobre **una sombrita que entra y sale conmigo**.', fr: 'Stevenson chantait **une petite ombre qui entre et sort avec moi**.' },
  { s: 'summer', t: 'evening', ko: '에밀리 브론테는 온화한 하늘 아래 **풀 사이로 부드럽게 숨 쉬는 바람**을 들었어요.', en: 'Under a benign sky, Emily Brontë listened to **the soft wind breathing through the grass**.', ja: 'エミリー・ブロンテはおだやかな空の下で、**草のあいだをやさしく吹きぬける風の息**を聞きました。', es: 'Bajo un cielo apacible, Emily Brontë escuchó **el viento suave que respira entre la hierba**.', fr: 'Sous un ciel bienveillant, Emily Brontë écoutait **le vent doux qui respire dans l’herbe**.' },
  { s: 'summer', ko: '바쇼는 **여름 풀이여, 옛 무사들 꿈의 자취**라고 읊었어요.', en: 'Bashō wrote, **summer grasses, all that remains of warriors’ dreams**.', ja: '芭蕉は、**夏草や兵どもが夢の跡**と詠みました。', es: 'Bashō escribió: **hierbas de verano, lo que queda de los sueños de los guerreros**.', fr: 'Bashō a écrit : **herbes d’été, ce qui reste des rêves des guerriers**.' },
  // ── 예술가의 말
  { t: 'night', w: 'clear', ko: '반 고흐는 **별을 보면 꿈을 꾸게 된다**고 했어요.', en: 'Van Gogh said that **the sight of the stars makes me dream**.', ja: 'ゴッホは、**星を見ると夢を見たくなる**と書きました。', es: 'Van Gogh dijo que **ver las estrellas le hacía soñar**.', fr: 'Van Gogh disait que **la vue des étoiles le faisait rêver**.' },
  { t: 'night', ko: '반 고흐는 **밤이 낮보다 더 풍부한 색**을 지녔다고 썼어요.', en: 'Van Gogh wrote that **the night is more richly coloured than the day**.', ja: 'ゴッホは、**夜は昼よりも豊かな色をしている**と書きました。', es: 'Van Gogh escribió que **la noche tiene colores más ricos que el día**.', fr: 'Van Gogh a écrit que **la nuit est plus richement colorée que le jour**.' },
  { ko: '반 고흐는 **자연을 정말 사랑하면 어디서나 아름다움을 찾게 된다**고 했어요.', en: 'Van Gogh said that **if one truly loves nature, one finds beauty everywhere**.', ja: 'ゴッホは、**自然を本当に愛せば、どこにでも美しさが見つかる**と書きました。', es: 'Van Gogh dijo que **quien ama de verdad la naturaleza encuentra belleza en todas partes**.', fr: 'Van Gogh disait que **si l’on aime vraiment la nature, on trouve la beauté partout**.' },
  { w: 'clear', ko: '파울 클레는 튀니지의 빛 아래서 **색이 나를 사로잡았다**고 썼어요.', en: 'Under the light of Tunisia, Paul Klee wrote, **colour has taken possession of me**.', ja: 'パウル・クレーはチュニジアの光の下で、**色が私をとらえた**と書きました。', es: 'Bajo la luz de Túnez, Paul Klee escribió: **el color se ha apoderado de mí**.', fr: 'Sous la lumière de Tunisie, Paul Klee a écrit : **la couleur me possède**.' },
  { ko: '칸딘스키는 **색은 건반이고 눈은 망치, 영혼은 현이 많은 피아노**라고 했어요.', en: 'Kandinsky said, **colour is the keyboard, the eyes are the hammers, the soul is the piano with many strings**.', ja: 'カンディンスキーは、**色は鍵盤、目はハンマー、魂は多くの弦をもつピアノ**と書きました。', es: 'Kandinsky dijo: **el color es el teclado, los ojos los martillos, el alma el piano de muchas cuerdas**.', fr: 'Kandinsky disait : **la couleur est la touche, l’œil le marteau, l’âme le piano aux cordes nombreuses**.' },
];

const SEASON = { spring: 1, summer: 1, autumn: 1, winter: 1 };
/* 오늘(날짜·시간대) 하나를 골라요. 계절·시간대·날씨가 맞을수록 먼저, 최근 2주에 나온 줄은 건너뛰어요 */
function pickLit(ctx, lang, seen = []) {
  const kind = ctx.weather?.kind; const wx = kind === 'sun' ? 'clear' : kind === 'rain' || kind === 'thunder' ? 'rain' : kind === 'snow' ? 'snow' : kind ? 'cloud' : '';
  const fits = LIT.map((x, i) => ({ x, i })).filter(({ x }) => x[lang] && (!x.s || x.s === ctx.season) && (!x.t || x.t === ctx.slot) && (!x.w || x.w === wx));
  const score = x => (x.s ? 2 : 0) + (x.t ? 2 : 0) + (x.w ? 3 : 0);
  const fresh = fits.filter(({ i }) => !seen.includes(i));
  const pool = fresh.length ? fresh : fits;
  if (!pool.length) return null;
  // 계절·시간대·날씨가 맞을수록 자주 나와요 (언제든 어울리는 줄도 가끔)
  const weight = x => 1 + score(x) * 2, total = pool.reduce((n, { x }) => n + weight(x), 0);
  let h = 0; for (const c of ctx.today + ctx.slot) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  h ^= h >>> 16; h = Math.imul(h, 0x45d9f3b) >>> 0; h ^= h >>> 16;
  let r = h % total, pick = pool[0];
  for (const it of pool) { r -= weight(it.x); if (r < 0) { pick = it; break; } }
  return { i: pick.i, html: pick.x[lang] };
}

export { LIT, SEASON, pickLit };
